-- DAROU SALAM — migration basée sur le diagnostic PostgreSQL fourni le 12/09/2026.
-- À exécuter UNE FOIS, en entier, dans SQL Editor. Transaction atomique.
-- Aucune suppression de données métier. Les anciens accès sont remplacés.
BEGIN;
SET LOCAL lock_timeout = '10s';

DO $$ BEGIN
  IF to_regclass('public.shops') IS NOT NULL THEN
    RAISE EXCEPTION 'shops existe déjà : migration déjà appliquée ou nouveau diagnostic nécessaire';
  END IF;
  IF (SELECT count(*) FROM information_schema.tables WHERE table_schema='public'
      AND table_type='BASE TABLE') <> 5 THEN
    RAISE EXCEPTION 'La liste des tables a changé depuis le diagnostic';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public'
      AND table_name='produits' AND column_name='stock_quantite' AND data_type='integer')
     OR NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public'
      AND table_name='ventes' AND column_name='produit_id' AND data_type='uuid') THEN
    RAISE EXCEPTION 'Structure différente du diagnostic';
  END IF;
END $$;
LOCK TABLE public.categories, public.produits, public.customers, public.ventes, public.profiles IN ACCESS EXCLUSIVE MODE;
CREATE TEMP TABLE migration_counts ON COMMIT DROP AS
SELECT 'categories' AS name, count(*) AS n FROM public.categories UNION ALL
SELECT 'produits', count(*) FROM public.produits UNION ALL
SELECT 'customers', count(*) FROM public.customers UNION ALL
SELECT 'ventes', count(*) FROM public.ventes UNION ALL
SELECT 'profiles', count(*) FROM public.profiles;

CREATE TABLE public.shops (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nom text NOT NULL,
 code text NOT NULL UNIQUE, type_activite text NOT NULL,
 active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.shops(id,nom,code,type_activite) VALUES
 ('00000000-0000-4000-8000-000000000001','Boutique Khady Faye','KHF','Dialabès'),
 ('00000000-0000-4000-8000-000000000002','Boutique Adama Faye','ADF','Tissus et autres produits'),
 ('00000000-0000-4000-8000-000000000003','Boutique Amary Faye','AMF','Vaisselle');
CREATE TABLE public.profile_shops (
 profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 shop_id uuid NOT NULL REFERENCES public.shops(id), PRIMARY KEY(profile_id,shop_id)
);
-- Personnel existant : uniquement Khady. Les administrateurs ont accès aux trois.
INSERT INTO public.profile_shops SELECT id,'00000000-0000-4000-8000-000000000001'::uuid
 FROM public.profiles WHERE role <> 'admin';
ALTER TABLE public.profiles DROP CONSTRAINT profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK(role IN ('admin','vendeuse','personnel'));

DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['categories','produits','customers','ventes'] LOOP
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN shop_id uuid REFERENCES public.shops(id)',t);
  EXECUTE format('UPDATE public.%I SET shop_id = %L::uuid',t,'00000000-0000-4000-8000-000000000001');
  EXECUTE format('ALTER TABLE public.%I ALTER COLUMN shop_id SET NOT NULL',t);
  EXECUTE format('ALTER TABLE public.%I ADD UNIQUE(id,shop_id)',t);
  EXECUTE format('CREATE INDEX ON public.%I(shop_id)',t);
 END LOOP;
END $$;
ALTER TABLE public.categories DROP CONSTRAINT categories_nom_key;
ALTER TABLE public.categories ADD UNIQUE(shop_id,nom);
ALTER TABLE public.produits ADD COLUMN purchase_price numeric(12,2) CHECK(purchase_price >= 0),
 ADD COLUMN reference text, ADD COLUMN photo_path text,
 ADD COLUMN reserved_quantity integer NOT NULL DEFAULT 0 CHECK(reserved_quantity >= 0),
 ADD CHECK(stock_quantite >= reserved_quantity),
 ADD FOREIGN KEY(categorie_id,shop_id) REFERENCES public.categories(id,shop_id);
ALTER TABLE public.customers ADD COLUMN notes text;
ALTER TABLE public.ventes ADD COLUMN customer_id bigint,
 ADD COLUMN cancelled_at timestamptz,
 ADD FOREIGN KEY(produit_id,shop_id) REFERENCES public.produits(id,shop_id),
 ADD FOREIGN KEY(customer_id,shop_id) REFERENCES public.customers(id,shop_id);

INSERT INTO public.categories(nom,shop_id)
 SELECT x.nom,s.id FROM public.shops s CROSS JOIN LATERAL (
  SELECT unnest(CASE s.code WHEN 'KHF' THEN ARRAY['Dialabès','Foulards','Voiles','Accessoires']
  WHEN 'ADF' THEN ARRAY['Tissus','Autres textiles'] ELSE ARRAY['Vaisselle','Articles de maison'] END) AS nom
 ) x ON CONFLICT(shop_id,nom) DO NOTHING;

CREATE TABLE public.reservations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 shop_id uuid NOT NULL REFERENCES public.shops(id), product_id uuid NOT NULL,
 customer_id bigint NOT NULL, quantity integer NOT NULL CHECK(quantity>0),
 unit_price numeric(12,2) NOT NULL CHECK(unit_price>=0),
 total_amount numeric(12,2) GENERATED ALWAYS AS(quantity*unit_price) STORED,
 paid_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK(paid_amount>=0),
 remaining_amount numeric(12,2) GENERATED ALWAYS AS(quantity*unit_price-paid_amount) STORED,
 status text NOT NULL CHECK(status IN ('en_cours','paye','remis','annule')),
 note text, reserved_at timestamptz NOT NULL DEFAULT now(),
 created_by uuid NOT NULL REFERENCES public.profiles(id),
 sale_id uuid UNIQUE REFERENCES public.ventes(id),
 CHECK(paid_amount<=quantity*unit_price), UNIQUE(id,shop_id),
 FOREIGN KEY(product_id,shop_id) REFERENCES public.produits(id,shop_id),
 FOREIGN KEY(customer_id,shop_id) REFERENCES public.customers(id,shop_id)
);
CREATE TABLE public.payments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 shop_id uuid NOT NULL REFERENCES public.shops(id), reservation_id bigint NOT NULL,
 amount numeric(12,2) NOT NULL CHECK(amount<>0), note text,
 created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL REFERENCES public.profiles(id),
 FOREIGN KEY(reservation_id,shop_id) REFERENCES public.reservations(id,shop_id)
);
-- Versement = remise d'argent à l'administratrice, distincte du paiement client.
CREATE TABLE public.versements (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 shop_id uuid NOT NULL REFERENCES public.shops(id), amount numeric(12,2) NOT NULL CHECK(amount>0),
 note text, created_at timestamptz NOT NULL DEFAULT now(),
 created_by uuid NOT NULL REFERENCES public.profiles(id)
);
CREATE TABLE public.factures (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shop_id uuid NOT NULL REFERENCES public.shops(id),
 sale_id uuid NOT NULL UNIQUE, numero text NOT NULL UNIQUE,
 shop_name text NOT NULL, product_name text NOT NULL, customer_name text NOT NULL,
 quantity integer NOT NULL, unit_price numeric(12,2) NOT NULL, total_amount numeric(12,2) NOT NULL,
 purchase_price numeric(12,2), issued_at timestamptz NOT NULL, legacy boolean NOT NULL DEFAULT false,
 FOREIGN KEY(sale_id,shop_id) REFERENCES public.ventes(id,shop_id)
);
CREATE TABLE public.invoice_counters (
 shop_id uuid NOT NULL REFERENCES public.shops(id), year integer NOT NULL,
 value bigint NOT NULL, PRIMARY KEY(shop_id,year)
);
CREATE TABLE public.audit_logs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 shop_id uuid NOT NULL REFERENCES public.shops(id), user_id uuid REFERENCES public.profiles(id),
 action text NOT NULL, table_name text NOT NULL, record_id text, details jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['reservations','payments','versements','factures','audit_logs'] LOOP
  EXECUTE format('CREATE INDEX ON public.%I(shop_id)',t);
 END LOOP;
END $$;
-- Aucune table de factures n'existait : archives initiales des ventes anciennes.
-- Le nom historique avant migration ne peut pas être reconstruit après un renommage passé.
INSERT INTO public.factures(shop_id,sale_id,numero,shop_name,product_name,customer_name,
 quantity,unit_price,total_amount,issued_at,legacy)
 SELECT v.shop_id,v.id,'KHF-ARCHIVE-'||v.id,s.nom,p.nom_modele,'Client comptant',
 v.quantite,v.prix_unitaire,v.montant_total,v.date_vente,true
 FROM public.ventes v JOIN public.produits p ON p.id=v.produit_id JOIN public.shops s ON s.id=v.shop_id;

CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=''
 AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND role='admin' AND active IS TRUE) $$;
CREATE FUNCTION public.can_access_shop(p_shop_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=''
 AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles p JOIN public.shops s ON s.id=p_shop_id AND s.active
 WHERE p.id=auth.uid() AND p.active IS TRUE AND (p.role='admin' OR EXISTS(
 SELECT 1 FROM public.profile_shops ps WHERE ps.profile_id=p.id AND ps.shop_id=s.id))) $$;
CREATE FUNCTION public.require_shop(p_shop_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=''
 AS $$ BEGIN IF NOT public.can_access_shop(p_shop_id) THEN RAISE EXCEPTION 'Accès refusé à cette boutique'; END IF; END $$;

-- Remplacement exhaustif des anciennes policies : les permissives s'additionnent.
DO $$ DECLARE p record; t text; BEGIN
 FOR p IN SELECT * FROM pg_policies WHERE schemaname='public' LOOP
  EXECUTE format('DROP POLICY %I ON public.%I',p.policyname,p.tablename);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['shops','profile_shops','profiles','categories','produits','customers','ventes',
 'reservations','payments','versements','factures','invoice_counters','audit_logs'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, anon, authenticated',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['categories','produits','customers','ventes','reservations','payments','versements','factures','audit_logs'] LOOP
  EXECUTE format('GRANT SELECT ON public.%I TO authenticated',t);
  EXECUTE format('CREATE POLICY shop_read ON public.%I FOR SELECT TO authenticated USING(public.can_access_shop(shop_id))',t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['categories','produits','customers'] LOOP
  EXECUTE format('GRANT INSERT, UPDATE, DELETE ON public.%I TO authenticated',t);
  EXECUTE format('CREATE POLICY shop_write ON public.%I FOR ALL TO authenticated USING(public.can_access_shop(shop_id) AND %s) WITH CHECK(public.can_access_shop(shop_id) AND %s)',
   t,CASE WHEN t='customers' THEN 'true' ELSE 'public.is_admin()' END,CASE WHEN t='customers' THEN 'true' ELSE 'public.is_admin()' END);
 END LOOP;
END $$;
GRANT SELECT ON public.shops,public.profile_shops,public.profiles TO authenticated;
GRANT UPDATE(nom,type_activite,active) ON public.shops TO authenticated;
CREATE POLICY shops_read ON public.shops FOR SELECT TO authenticated USING(public.can_access_shop(id));
CREATE POLICY shops_update ON public.shops FOR UPDATE TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
CREATE POLICY memberships_read ON public.profile_shops FOR SELECT TO authenticated USING(profile_id=auth.uid() OR public.is_admin());
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.is_admin());
GRANT UPDATE(active) ON public.profiles TO authenticated;
CREATE POLICY profiles_active ON public.profiles FOR UPDATE TO authenticated USING(public.is_admin() AND id<>auth.uid()) WITH CHECK(public.is_admin());
GRANT INSERT ON public.audit_logs TO authenticated;
CREATE POLICY audit_insert ON public.audit_logs FOR INSERT TO authenticated WITH CHECK(public.can_access_shop(shop_id) AND user_id=auth.uid());
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

CREATE FUNCTION public.prevent_shop_move() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF new.shop_id IS DISTINCT FROM old.shop_id THEN RAISE EXCEPTION 'Le rattachement à la boutique est immuable'; END IF;
 RETURN new; END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['categories','produits','customers','ventes','reservations','payments','versements','factures','audit_logs'] LOOP
 EXECUTE format('CREATE TRIGGER immutable_shop BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.prevent_shop_move()',t);
 END LOOP;
END $$;
CREATE FUNCTION public.set_staff_shops(p_profile_id uuid,p_shop_ids uuid[]) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Administratrice uniquement'; END IF;
 PERFORM 1 FROM public.profiles WHERE id=p_profile_id AND role IN ('vendeuse','personnel') FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Personnel introuvable'; END IF;
 IF p_shop_ids IS NULL OR EXISTS(SELECT 1 FROM unnest(p_shop_ids) x WHERE x IS NULL OR NOT EXISTS(
 SELECT 1 FROM public.shops s WHERE s.id=x AND s.active)) THEN RAISE EXCEPTION 'Boutiques invalides'; END IF;
 DELETE FROM public.profile_shops WHERE profile_id=p_profile_id;
 INSERT INTO public.profile_shops SELECT p_profile_id,x FROM (SELECT DISTINCT unnest(p_shop_ids) x) a;
 END $$;

-- Le trigger existant reste responsable de l'unique déduction du stock.
CREATE OR REPLACE FUNCTION public.deduire_stock_apres_vente() RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 PERFORM public.require_shop(new.shop_id);
 UPDATE public.produits SET stock_quantite=stock_quantite-new.quantite,updated_at=now()
 WHERE id=new.produit_id AND shop_id=new.shop_id AND actif AND stock_quantite-reserved_quantity>=new.quantite;
 IF NOT FOUND THEN RAISE EXCEPTION 'Stock disponible insuffisant'; END IF;
 RETURN new; END $$;
CREATE FUNCTION public.issue_invoice() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
 DECLARE n bigint; y integer; s public.shops; p public.produits; c text;
 BEGIN
 SELECT * INTO s FROM public.shops WHERE id=new.shop_id;
 SELECT * INTO p FROM public.produits WHERE id=new.produit_id;
 SELECT nom INTO c FROM public.customers WHERE id=new.customer_id;
 y:=extract(year FROM new.date_vente AT TIME ZONE 'Africa/Dakar');
 INSERT INTO public.invoice_counters VALUES(new.shop_id,y,1) ON CONFLICT(shop_id,year)
 DO UPDATE SET value=public.invoice_counters.value+1 RETURNING value INTO n;
 INSERT INTO public.factures(shop_id,sale_id,numero,shop_name,product_name,customer_name,
 quantity,unit_price,total_amount,purchase_price,issued_at)
 VALUES(new.shop_id,new.id,s.code||'-'||y||'-'||lpad(n::text,greatest(6,length(n::text)),'0'),s.nom,p.nom_modele,
 coalesce(c,'Client comptant'),new.quantite,new.prix_unitaire,new.montant_total,p.purchase_price,new.date_vente);
 RETURN new; END $$;
CREATE TRIGGER invoice_after_sale AFTER INSERT ON public.ventes FOR EACH ROW EXECUTE FUNCTION public.issue_invoice();
CREATE FUNCTION public.create_sale(p_shop_id uuid,p_product_id uuid,p_customer_id bigint,p_quantity integer,p_unit_price numeric)
 RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE v uuid; BEGIN
 PERFORM public.require_shop(p_shop_id);
 IF p_quantity IS NULL OR p_quantity<=0 OR p_unit_price IS NULL OR p_unit_price<0 THEN RAISE EXCEPTION 'Vente invalide'; END IF;
 INSERT INTO public.ventes(shop_id,produit_id,customer_id,quantite,prix_unitaire,mode_paiement,vendeuse_id)
 VALUES(p_shop_id,p_product_id,p_customer_id,p_quantity,p_unit_price,'especes',auth.uid()) RETURNING id INTO v;
 RETURN v; END $$;
CREATE FUNCTION public.restock_product(p_shop_id uuid,p_product_id uuid,p_quantity integer) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 PERFORM public.require_shop(p_shop_id);
 IF NOT public.is_admin() OR p_quantity IS NULL OR p_quantity<=0 THEN RAISE EXCEPTION 'Réapprovisionnement refusé'; END IF;
 UPDATE public.produits SET stock_quantite=stock_quantite+p_quantity WHERE id=p_product_id AND shop_id=p_shop_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Produit introuvable'; END IF; END $$;
-- Anciennes RPC non sécurisées désactivées, nouvelles signatures explicites.
REVOKE EXECUTE ON FUNCTION public.supprimer_vente(uuid),public.supprimer_vente_admin(uuid) FROM PUBLIC,anon,authenticated;
CREATE FUNCTION public.supprimer_vente_admin(p_shop_id uuid,p_vente_id uuid) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE v public.ventes; BEGIN
 PERFORM public.require_shop(p_shop_id);
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Administratrice uniquement'; END IF;
 SELECT * INTO v FROM public.ventes WHERE id=p_vente_id AND shop_id=p_shop_id FOR UPDATE;
 IF NOT FOUND OR v.cancelled_at IS NOT NULL THEN RAISE EXCEPTION 'Vente absente ou déjà annulée'; END IF;
 IF EXISTS(SELECT 1 FROM public.reservations WHERE sale_id=v.id) THEN RAISE EXCEPTION 'Une réservation remise ne peut pas être annulée comme vente comptant'; END IF;
 UPDATE public.produits SET stock_quantite=stock_quantite+v.quantite WHERE id=v.produit_id AND shop_id=p_shop_id;
 UPDATE public.ventes SET cancelled_at=now() WHERE id=v.id;
 END $$;

CREATE FUNCTION public.create_reservation(p_shop_id uuid,p_customer_id bigint,p_product_id uuid,p_quantity integer,p_advance numeric,p_note text)
 RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE p public.produits; r bigint; BEGIN
 PERFORM public.require_shop(p_shop_id);
 SELECT * INTO p FROM public.produits WHERE id=p_product_id AND shop_id=p_shop_id AND actif FOR UPDATE;
 IF NOT FOUND OR p_quantity IS NULL OR p_quantity<=0 OR p.stock_quantite-p.reserved_quantity<p_quantity
 OR p_advance IS NULL OR p_advance<0 OR p_advance>p.prix*p_quantity THEN RAISE EXCEPTION 'Réservation ou stock disponible invalide'; END IF;
 INSERT INTO public.reservations(shop_id,customer_id,product_id,quantity,unit_price,paid_amount,status,note,created_by)
 VALUES(p_shop_id,p_customer_id,p_product_id,p_quantity,p.prix,p_advance,
 CASE WHEN p_advance=p.prix*p_quantity THEN 'paye' ELSE 'en_cours' END,p_note,auth.uid()) RETURNING id INTO r;
 UPDATE public.produits SET reserved_quantity=reserved_quantity+p_quantity WHERE id=p.id;
 IF p_advance>0 THEN INSERT INTO public.payments(shop_id,reservation_id,amount,note,created_by)
 VALUES(p_shop_id,r,p_advance,'Avance',auth.uid()); END IF;
 RETURN r; END $$;
CREATE FUNCTION public.add_payment(p_shop_id uuid,p_reservation_id bigint,p_amount numeric,p_note text) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE r public.reservations; BEGIN
 PERFORM public.require_shop(p_shop_id);
 SELECT * INTO r FROM public.reservations WHERE id=p_reservation_id AND shop_id=p_shop_id FOR UPDATE;
 IF NOT FOUND OR r.status<>'en_cours' OR p_amount IS NULL OR p_amount<=0 OR p_amount>r.remaining_amount THEN RAISE EXCEPTION 'Paiement invalide'; END IF;
 UPDATE public.reservations SET paid_amount=paid_amount+p_amount,
 status=CASE WHEN paid_amount+p_amount=total_amount THEN 'paye' ELSE 'en_cours' END WHERE id=r.id;
 INSERT INTO public.payments(shop_id,reservation_id,amount,note,created_by) VALUES(p_shop_id,r.id,p_amount,p_note,auth.uid());
 END $$;
CREATE FUNCTION public.mark_reservation_remis(p_shop_id uuid,p_reservation_id bigint) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE r public.reservations; v uuid; BEGIN
 PERFORM public.require_shop(p_shop_id);
 SELECT * INTO r FROM public.reservations WHERE id=p_reservation_id AND shop_id=p_shop_id FOR UPDATE;
 IF NOT FOUND OR r.status<>'paye' THEN RAISE EXCEPTION 'Réservation non payée ou déjà remise'; END IF;
 UPDATE public.produits SET reserved_quantity=reserved_quantity-r.quantity WHERE id=r.product_id AND shop_id=p_shop_id;
 v:=public.create_sale(p_shop_id,r.product_id,r.customer_id,r.quantity,r.unit_price);
 UPDATE public.reservations SET status='remis',sale_id=v WHERE id=r.id;
 END $$;
CREATE FUNCTION public.cancel_reservation(p_shop_id uuid,p_reservation_id bigint) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE r public.reservations; BEGIN
 PERFORM public.require_shop(p_shop_id);
 SELECT * INTO r FROM public.reservations WHERE id=p_reservation_id AND shop_id=p_shop_id FOR UPDATE;
 IF NOT FOUND OR r.status NOT IN ('en_cours','paye') THEN RAISE EXCEPTION 'Annulation impossible'; END IF;
 -- Un remboursement doit être explicite : ne jamais inventer une sortie de caisse.
 IF r.paid_amount>0 THEN RAISE EXCEPTION 'Réservation avec paiement : remboursement à traiter avant annulation'; END IF;
 UPDATE public.produits SET reserved_quantity=reserved_quantity-r.quantity WHERE id=r.product_id;
 UPDATE public.reservations SET status='annule' WHERE id=r.id;
 END $$;
CREATE FUNCTION public.record_versement(p_shop_id uuid,p_amount numeric,p_note text) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 PERFORM public.require_shop(p_shop_id);
 IF p_amount IS NULL OR p_amount<=0 THEN RAISE EXCEPTION 'Montant invalide'; END IF;
 INSERT INTO public.versements(shop_id,amount,note,created_by) VALUES(p_shop_id,p_amount,p_note,auth.uid()); END $$;

-- Ne pas effacer le personnel lié aux archives : désactivation conservant les ventes.
CREATE OR REPLACE FUNCTION public.supprimer_personnel_admin(p_user_id uuid) RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ BEGIN
 IF NOT public.is_admin() OR p_user_id=auth.uid() THEN RAISE EXCEPTION 'Action refusée'; END IF;
 UPDATE public.profiles SET active=false WHERE id=p_user_id AND role IN ('personnel','vendeuse');
 IF NOT FOUND THEN RAISE EXCEPTION 'Personnel introuvable'; END IF;
 DELETE FROM public.profile_shops WHERE profile_id=p_user_id;
 END $$;
DO $$ DECLARE f record; BEGIN
 FOR f IN SELECT p.oid::regprocedure AS sig,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
 WHERE n.nspname='public' AND p.proname IN ('is_admin','can_access_shop','require_shop','set_staff_shops',
 'prevent_shop_move','issue_invoice','deduire_stock_apres_vente','create_sale','restock_product',
 'create_reservation','add_payment','mark_reservation_remis','cancel_reservation','record_versement',
 'supprimer_personnel_admin','modifier_mon_nom') LOOP
  EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC,anon,authenticated',f.sig);
  IF f.proname NOT IN ('require_shop','prevent_shop_move','issue_invoice','deduire_stock_apres_vente') THEN
   EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated',f.sig);
  END IF;
 END LOOP;
END $$;
REVOKE EXECUTE ON FUNCTION public.supprimer_vente_admin(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.supprimer_vente_admin(uuid,uuid) TO authenticated;

DO $$ DECLARE r record; actual bigint; BEGIN
 FOR r IN SELECT * FROM migration_counts LOOP
  EXECUTE format('SELECT count(*) FROM public.%I',r.name) INTO actual;
  IF actual<r.n OR (r.name<>'categories' AND actual<>r.n) THEN RAISE EXCEPTION 'Nombre de lignes modifié : %',r.name; END IF;
 END LOOP;
END $$;
NOTIFY pgrst,'reload schema';
COMMIT;

-- Résultat de contrôle visible dans SQL Editor après installation réussie.
SELECT s.nom,
 (SELECT count(*) FROM public.produits p WHERE p.shop_id=s.id) AS produits,
 (SELECT count(*) FROM public.customers c WHERE c.shop_id=s.id) AS clients,
 (SELECT count(*) FROM public.ventes v WHERE v.shop_id=s.id) AS ventes,
 (SELECT count(*) FROM public.factures f WHERE f.shop_id=s.id) AS factures
FROM public.shops s ORDER BY s.code;
