const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const kh='00000000-0000-4000-8000-000000000001',ad='00000000-0000-4000-8000-000000000002';
const admin='10000000-0000-4000-8000-000000000001',staff='10000000-0000-4000-8000-000000000002';
const p='20000000-0000-4000-8000-000000000001',cat='30000000-0000-4000-8000-000000000001';
const qi=s=>'"'+s.replaceAll('"','""')+'"';
test('mètres : conservation, précision, commandes, réservations, RLS et annulation',async t=>{
 const db=new PGlite();try{
 const fixture=JSON.parse(fs.readFileSync('tests/schema-before.json','utf8').replace(/^\uFEFF/,''));
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$; GRANT USAGE ON SCHEMA auth TO authenticated,anon;
 CREATE FUNCTION uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;`);
 for(const r of fixture.relations)await db.exec(`CREATE TABLE public.${qi(r.name)} (${r.columns.map(c=>qi(c.name)+' '+c.type+(c.generated?` GENERATED ALWAYS AS (${c.default}) STORED`:c.identity?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:'')+(c.not_null?' NOT NULL':'')).join(',')})`);
 for(const type of ['p','u','c','f'])for(const r of fixture.relations)for(const c of r.constraints.filter(c=>c.type===type))await db.exec(`ALTER TABLE public.${qi(r.name)} ADD CONSTRAINT ${qi(c.name)} ${c.definition}`);
 for(const f of fixture.functions)await db.exec(f.definition);for(const r of fixture.relations)for(const trig of r.triggers)await db.exec(trig);
 await db.exec(`INSERT INTO auth.users VALUES('${admin}'),('${staff}');INSERT INTO profiles(id,nom_complet,role) VALUES('${admin}','Admin','admin'),('${staff}','Personnel','vendeuse');
 INSERT INTO categories(id,nom) VALUES('${cat}','Ancienne catégorie');INSERT INTO produits(id,categorie_id,nom_modele,prix,stock_quantite) VALUES('${p}','${cat}','Ancien produit',100,10);
 INSERT INTO ventes(produit_id,quantite,prix_unitaire,mode_paiement,vendeuse_id) VALUES('${p}',2,100,'especes','${admin}');`);
 await db.exec(fs.readFileSync('supabase/migration-multi-boutiques.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/reprise-ventes-multi-produits.sql','utf8'));
 const migration=fs.readFileSync('supabase/migration-unites-metres.sql','utf8');
 const scalar=async sql=>(await db.query(sql)).rows[0];
 const login=async id=>db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${id}',false); SET ROLE authenticated;`);
 const fail=sql=>assert.rejects(db.exec(sql));
 await t.test('migration réexécutable sans modification des valeurs historiques',async()=>{
  const old=(await scalar('SELECT to_jsonb(f) j FROM factures f')).j;
  await db.exec(migration);await db.exec(migration);
  assert.deepEqual((await scalar("SELECT to_jsonb(f)-'unit' j FROM factures f")).j,old);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${p}'`)).n),8);
  assert.equal((await scalar(`SELECT unit FROM produits WHERE id='${p}'`)).unit,'piece');
 });
 await login(admin);
 const catAd=(await scalar(`SELECT id FROM categories WHERE shop_id='${ad}' LIMIT 1`)).id;
 const metre=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,purchase_price,stock_quantite,unit) VALUES('${ad}','${catAd}','Tissu X',2500,1500,50,'metre') RETURNING id`)).id;
 const piece=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,purchase_price,stock_quantite) VALUES('${ad}','${catAd}','Accessoire',100,50,10) RETURNING id`)).id;
 const order=async items=>(await scalar(`SELECT create_sale_order('${ad}',null,'${JSON.stringify(items)}',gen_random_uuid()) id`)).id;
 await t.test('50 m moins 3,5 m = 46,5 m ; facture 8 750 F puis restauration',async()=>{
  const id=await order([{product_id:metre,quantity:3.5,unit_price:2500}]);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),46.5);
  const f=await scalar(`SELECT * FROM factures WHERE sale_id='${id}'`);
  assert.equal(Number(f.total_amount),8750);assert.equal(f.items[0].unit,'metre');assert.equal(f.items[0].quantity,3.5);
  assert.equal((await scalar(`SELECT unit FROM vente_lignes WHERE sale_id='${id}'`)).unit,'metre');
  await db.exec(`SELECT supprimer_vente_admin('${ad}','${id}')`);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),50);
  await fail(`SELECT supprimer_vente_admin('${ad}','${id}')`);
 });
 await t.test('commande mixte, fractions interdites sur pièces, précision et atomicité',async()=>{
  await order([{product_id:metre,quantity:2.25,unit_price:2500},{product_id:piece,quantity:2,unit_price:100}]);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),47.75);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${piece}'`)).n),8);
  for(const items of [[{product_id:piece,quantity:1.5,unit_price:100}],
   [{product_id:metre,quantity:0.001,unit_price:2500}],
   [{product_id:metre,quantity:1,unit_price:2500},{product_id:piece,quantity:99,unit_price:100}]])await assert.rejects(order(items));
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),47.75);
  await db.exec(`SELECT restock_product_measured('${ad}','${metre}',0.25)`);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),48);
  await fail(`SELECT restock_product_measured('${ad}','${piece}',0.5)`);
  await fail(`UPDATE produits SET stock_quantite=1.5 WHERE id='${piece}'`);
  await fail(`UPDATE produits SET unit='metre' WHERE id='${piece}'`);
 });
 await t.test('réservation 1,25 m : paiement, remise, facture et stocks cohérents',async()=>{
  const c=(await scalar(`INSERT INTO customers(nom,shop_id) VALUES('Cliente','${ad}') RETURNING id`)).id;
  const r=(await scalar(`SELECT create_reservation_measured('${ad}',${c},'${metre}',1.25,1000,'Test') id`)).id;
  const reservation=await scalar(`SELECT * FROM reservations WHERE id=${r}`);
  assert.equal(Number(reservation.total_amount),3125);assert.equal(Number(reservation.remaining_amount),2125);
  assert.equal(reservation.unit,'metre');
  await db.exec(`SELECT add_payment('${ad}',${r},2125,'Solde'); SELECT mark_reservation_remis('${ad}',${r});`);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),46.75);
  assert.equal(Number((await scalar(`SELECT reserved_quantity n FROM produits WHERE id='${metre}'`)).n),0);
  const f=await scalar(`SELECT items,unit FROM factures WHERE sale_id=(SELECT sale_id FROM reservations WHERE id=${r})`);
  assert.equal(f.unit,'metre');
  assert.equal(f.items[0].quantity,1.25);assert.equal(f.items[0].unit,'metre');
 });
 await t.test('réexécution après ventes et réservations au mètre conserve tout',async()=>{
  await db.exec('RESET ROLE');
  const before=(await scalar(`SELECT jsonb_agg(to_jsonb(f) ORDER BY id) j FROM factures f`)).j;
  await db.exec(migration);
  assert.deepEqual((await scalar(`SELECT jsonb_agg(to_jsonb(f) ORDER BY id) j FROM factures f`)).j,before);
  assert.equal(Number((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${metre}'`)).n),46.75);
  await login(admin);
 });
 await t.test('anciens produits, droits par boutique et accès anonyme préservés',async()=>{
  await db.exec(`SELECT create_sale('${kh}','${p}',null,1,100)`);
  await login(staff);
  await fail(`SELECT restock_product_measured('${ad}','${metre}',1)`);
  await assert.rejects(order([{product_id:metre,quantity:1,unit_price:2500}]));
  await db.exec('RESET ROLE; SET ROLE anon');
  await fail(`SELECT create_sale_measured('${ad}','${metre}',null,1.5,2500)`);
  await fail('SELECT * FROM vente_lignes');
 });
 }finally{await db.close();}
});
