const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {PGlite} = require('@electric-sql/pglite');
const fixture = JSON.parse(fs.readFileSync('tests/schema-before.json','utf8').replace(/^\uFEFF/,''));
const kh='00000000-0000-4000-8000-000000000001', ad='00000000-0000-4000-8000-000000000002', am='00000000-0000-4000-8000-000000000003';
const admin='10000000-0000-4000-8000-000000000001', staff='10000000-0000-4000-8000-000000000002';
const prod='20000000-0000-4000-8000-000000000001', cat='30000000-0000-4000-8000-000000000001';
const qid = s=>'"'+s.replaceAll('"','""')+'"';
test('migration réelle : conservation, RLS, RPC, factures et réservations',async t=>{
 const db=new PGlite();
 try {
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$;
 GRANT USAGE ON SCHEMA auth TO authenticated,anon;
 CREATE FUNCTION public.uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;`);
 for(const r of fixture.relations){
   await db.exec(`CREATE TABLE public.${qid(r.name)} (${r.columns.map(c=>qid(c.name)+' '+c.type+
     (c.generated?` GENERATED ALWAYS AS (${c.default}) STORED`:c.identity?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:'')+
     (c.not_null?' NOT NULL':'')).join(',')})`);
 }
 for(const type of ['p','u','c','f']) for(const r of fixture.relations) for(const c of r.constraints.filter(c=>c.type===type))
  await db.exec(`ALTER TABLE public.${qid(r.name)} ADD CONSTRAINT ${qid(c.name)} ${c.definition}`);
 for(const f of fixture.functions) await db.exec(f.definition);
 for(const r of fixture.relations) for(const trig of r.triggers) await db.exec(trig);
 for(const p of fixture.policies.filter(p=>p.schemaname==='public')) await db.exec(`CREATE POLICY ${qid(p.policyname)} ON public.${qid(p.tablename)} FOR ${p.cmd} TO ${p.roles.map(qid).join(',')}${p.qual?' USING ('+p.qual+')':''}${p.with_check?' WITH CHECK ('+p.with_check+')':''}`);
 await db.exec(`INSERT INTO auth.users VALUES('${admin}'),('${staff}');
 INSERT INTO public.profiles(id,nom_complet,role) VALUES('${admin}','Admin','admin'),('${staff}','Personnel','vendeuse');
 INSERT INTO public.categories(id,nom) VALUES('${cat}','Ancienne catégorie');
 INSERT INTO public.produits(id,categorie_id,nom_modele,prix,stock_quantite) VALUES('${prod}','${cat}','Ancien produit',500,30);
 INSERT INTO public.customers(nom) VALUES('Ancien client');
 INSERT INTO public.ventes(produit_id,quantite,prix_unitaire,mode_paiement,vendeuse_id) VALUES('${prod}',1,500,'especes','${staff}');`);
 await db.exec(fs.readFileSync('supabase/migration-multi-boutiques.sql','utf8'));
 const diagnosticSql=fs.readFileSync('supabase/diagnostic-reprise-ventes.sql','utf8');
 const initialDiagnostic=(await db.query(diagnosticSql)).rows[0].diagnostic;
 assert.equal(initialDiagnostic.tables.some(t=>t.table==='vente_lignes'),false);
 const before=await db.query('SELECT v.id,v.montant_total,p.stock_quantite,f.numero FROM ventes v JOIN produits p ON p.id=v.produit_id JOIN factures f ON f.sale_id=v.id');
 const migration=fs.readFileSync('supabase/migration-ventes-multi-produits.sql','utf8');
 const block=migration.match(/DO \$migration\$[\s\S]*?END \$migration\$;/)[0];
 const recovery=fs.readFileSync('supabase/reprise-ventes-multi-produits.sql','utf8');
 const recoveryBlock=recovery.match(/DO \$reprise\$[\s\S]*?END \$reprise\$;/)[0];
 const schemaOnly=migration.slice(migration.indexOf('ALTER TABLE public.ventes ALTER COLUMN produit_id'),migration.indexOf('-- Copie descriptive uniquement'));
 for(const [name,setup] of [
  ['base avant migration',''],
  ['une seule colonne déjà créée','ALTER TABLE public.ventes ADD COLUMN multi_produits boolean NOT NULL DEFAULT false;'],
  ['colonnes et table sans lignes',schemaOnly],
  ['migration entièrement appliquée',block],
  ['RLS et policy inachevés',schemaOnly+`ALTER TABLE public.vente_lignes DISABLE ROW LEVEL SECURITY; CREATE POLICY trop_large ON public.vente_lignes FOR ALL TO authenticated USING(true) WITH CHECK(true); GRANT ALL ON public.vente_lignes TO authenticated;`]
 ]) await t.test('reprise idempotente : '+name,async()=>{
  await db.exec('BEGIN');
  try {
   if(setup)await db.exec(setup);
   await db.exec(recoveryBlock);
   const read=async()=> (await db.query(`SELECT jsonb_build_object('ventes',(SELECT jsonb_agg(to_jsonb(v) ORDER BY id) FROM public.ventes v),
    'lignes',(SELECT jsonb_agg(to_jsonb(l) ORDER BY id) FROM public.vente_lignes l),
    'factures',(SELECT jsonb_agg(to_jsonb(f) ORDER BY id) FROM public.factures f),
    'produits',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM public.produits p)) AS snapshot`)).rows[0].snapshot;
   const first=await read();await db.exec(recoveryBlock);assert.deepEqual(await read(),first);
   assert.equal((await db.query('SELECT count(*)::int n FROM public.vente_lignes')).rows[0].n,1);
   assert.equal((await db.query(`SELECT stock_quantite n FROM public.produits WHERE id='${prod}'`)).rows[0].n,29);
   assert.equal((await db.query("SELECT relrowsecurity FROM pg_class WHERE oid='public.vente_lignes'::regclass")).rows[0].relrowsecurity,true);
   assert.equal((await db.query("SELECT count(*)::int n FROM pg_policies WHERE schemaname='public' AND tablename='vente_lignes'")).rows[0].n,1);
  } finally {await db.exec('ROLLBACK');}
 });
 await t.test('reprise : commande partiellement copiée et facture intacte',async()=>{
  await db.exec('BEGIN');
  try {
   await db.exec(block);
   await db.exec(`SELECT set_config('request.jwt.claim.sub','${admin}',true);`);
   const items=JSON.stringify([{product_id:prod,quantity:2,unit_price:500},{product_id:prod,quantity:1,unit_price:450}]);
   const id=(await db.query(`SELECT public.create_sale_order('${kh}',1,'${items}',gen_random_uuid()) id`)).rows[0].id;
   const invoice=(await db.query(`SELECT * FROM public.factures WHERE sale_id='${id}'`)).rows[0];
   const kept=(await db.query(`SELECT * FROM public.vente_lignes WHERE sale_id='${id}' AND position=1`)).rows[0];
   // Base fictive seulement : simule une copie interrompue, jamais envoyé à Supabase.
   await db.exec(`DELETE FROM public.vente_lignes WHERE sale_id='${id}' AND position=2`);
   const stock=(await db.query(`SELECT stock_quantite FROM public.produits WHERE id='${prod}'`)).rows[0].stock_quantite;
   await db.exec(recoveryBlock);await db.exec(recoveryBlock);
   assert.deepEqual((await db.query(`SELECT * FROM public.factures WHERE sale_id='${id}'`)).rows[0],invoice);
   assert.deepEqual((await db.query(`SELECT * FROM public.vente_lignes WHERE id='${kept.id}'`)).rows[0],kept);
   assert.equal((await db.query(`SELECT count(*)::int n FROM public.vente_lignes WHERE sale_id='${id}'`)).rows[0].n,2);
   assert.equal((await db.query(`SELECT stock_quantite FROM public.produits WHERE id='${prod}'`)).rows[0].stock_quantite,stock);
  }finally{await db.exec('ROLLBACK');}
 });
 await t.test('reprise : incohérence détectée sans écrasement des lignes existantes',async()=>{
  await db.exec('BEGIN');
  try {
   await db.exec(block);
   await db.exec('UPDATE public.vente_lignes SET quantity=2; SAVEPOINT tentative');
   await assert.rejects(db.exec(recoveryBlock),/total contradictoire/);
   await db.exec('ROLLBACK TO SAVEPOINT tentative');
   assert.equal((await db.query('SELECT quantity FROM public.vente_lignes')).rows[0].quantity,2);
   assert.equal((await db.query(`SELECT stock_quantite n FROM public.produits WHERE id='${prod}'`)).rows[0].n,29);
  }finally{await db.exec('ROLLBACK');}
 });
 await t.test('migration autonome : contrôle de conservation et retour arrière complet',async()=>{
  const corrupted=block.replace('-- Vérifications :',`UPDATE public.produits SET stock_quantite=stock_quantite+1;\n-- Vérifications :`);
  await assert.rejects(db.exec(corrupted),/Contrôle de conservation échoué/);
  assert.equal((await db.query("SELECT to_regclass('public.vente_lignes') AS relation")).rows[0].relation,null);
  assert.equal((await db.query(`SELECT stock_quantite n FROM public.produits WHERE id='${prod}'`)).rows[0].n,29);
 });
 await t.test('migration autonome : aucun schéma implicite ni table temporaire requis',async()=>{
  await db.exec("BEGIN; SET LOCAL search_path='';");
  try {
   await db.exec(block);
   assert.equal((await db.query('SELECT public.sales_api_version() AS version')).rows[0].version,2);
  } finally {await db.exec('ROLLBACK');}
 });
 await db.exec(migration);
 await db.exec(recovery);
 assert.equal((await db.query(diagnosticSql)).rows[0].diagnostic.tables.find(t=>t.table==='vente_lignes').rls,true);
 assert.deepEqual((await db.query('SELECT v.id,v.montant_total,p.stock_quantite,f.numero FROM ventes v JOIN produits p ON p.id=v.produit_id JOIN factures f ON f.sale_id=v.id')).rows,before.rows);
 await db.exec(`CREATE SCHEMA storage;
 CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text);
 ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
 GRANT USAGE ON SCHEMA storage TO authenticated;
 GRANT INSERT, SELECT ON storage.objects TO authenticated;`);
 await db.exec(fs.readFileSync('supabase/activer-photos-produits.sql','utf8'));
 const scalar=async sql=>(await db.query(sql)).rows[0];
 const login=async id=>{await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${id}',false); SET ROLE authenticated;`)};
 const fails=async sql=>{await assert.rejects(db.exec(sql));};
 await t.test('anciennes données conservées et rattachées à Khady',async()=>{
  assert.equal((await scalar(`SELECT count(*)::int n FROM ventes WHERE shop_id='${kh}'`)).n,1);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,29);
  assert.equal((await scalar('SELECT count(*)::int n FROM factures WHERE legacy')).n,1);
 });
 await login(admin);
 await t.test('photos privées : envoi admin, lecture par boutique et refus personnel',async()=>{
  await db.exec(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${admin}/photo.jpg'),('product-photos','${ad}/${admin}/photo.jpg')`);
  await login(staff);
  assert.equal((await scalar(`SELECT count(*)::int n FROM storage.objects`)).n,1);
  await fails(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${staff}/photo.jpg')`);
  await login(admin);
  await fails(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${staff}/photo.jpg')`);
 });
 let catAd=(await scalar(`SELECT id FROM categories WHERE shop_id='${ad}' LIMIT 1`)).id;
 let catAm=(await scalar(`SELECT id FROM categories WHERE shop_id='${am}' LIMIT 1`)).id;
 const prodAd=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,stock_quantite,purchase_price) VALUES('${ad}','${catAd}','Tissu',300,50,100) RETURNING id`)).id;
 const prodAm=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,stock_quantite) VALUES('${am}','${catAm}','Assiette',100,5) RETURNING id`)).id;
 await t.test('ventes séparées, déduction unique et accès global admin',async()=>{
  await db.exec(`SELECT create_sale('${kh}','${prod}',null,1,500); SELECT create_sale('${ad}','${prodAd}',null,1,300);`);
  assert.equal((await scalar(`SELECT sum(montant_total)::int n FROM ventes WHERE shop_id='${kh}'`)).n,1000);
  assert.equal((await scalar(`SELECT sum(montant_total)::int n FROM ventes WHERE shop_id='${ad}'`)).n,300);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,28);
  assert.equal((await scalar('SELECT count(*)::int n FROM shops')).n,3);
 });
 await t.test('factures figées après renommage et annulation sans effacement',async()=>{
  await db.exec(`UPDATE produits SET nom_modele='Tissu renommé',purchase_price=200 WHERE id='${prodAd}'; UPDATE shops SET nom='Adama renommée' WHERE id='${ad}'`);
  const inv=await scalar(`SELECT * FROM factures WHERE shop_id='${ad}'`);
  assert.equal(inv.product_name,'Tissu'); assert.equal(inv.shop_name,'Boutique Adama Faye'); assert.equal(Number(inv.purchase_price),100);
  await fails(`UPDATE factures SET product_name='Falsifié' WHERE id='${inv.id}'`);
  await db.exec(`SELECT supprimer_vente_admin('${ad}','${inv.sale_id}')`);
  assert.equal((await scalar(`SELECT count(*)::int n FROM factures WHERE id='${inv.id}'`)).n,1);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prodAd}'`)).n,50);
  await fails(`SELECT supprimer_vente_admin('${ad}','${inv.sale_id}')`);
 });
 await t.test('relations inter-boutiques et déplacement refusés même à admin',async()=>{
  await fails(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix) VALUES('${kh}','${catAd}','Intrus',1)`);
  await fails(`UPDATE produits SET shop_id='${ad}',categorie_id='${catAd}' WHERE id='${prod}'`);
  await fails(`SELECT create_sale('${kh}','${prodAd}',null,1,10)`);
 });
 await login(staff);
 await t.test('personnel : lecture et RPC limitées à Khady, privilèges inviolables',async()=>{
  assert.equal((await scalar('SELECT count(*)::int n FROM shops')).n,1);
  assert.equal((await scalar(`SELECT count(*)::int n FROM produits WHERE shop_id='${ad}'`)).n,0);
  assert.equal((await scalar(`SELECT count(*)::int n FROM factures WHERE shop_id='${ad}'`)).n,0);
  assert.equal((await scalar(`SELECT count(*)::int n FROM vente_lignes WHERE shop_id='${ad}'`)).n,0);
  await fails(`UPDATE vente_lignes SET quantity=99`);
  await fails(`SELECT create_sale('${ad}','${prodAd}',null,1,300)`);
  await fails(`INSERT INTO customers(nom,shop_id) VALUES('Intrus','${ad}')`);
  await fails(`UPDATE profiles SET role='admin' WHERE id='${staff}'`);
  await fails(`INSERT INTO profile_shops VALUES('${staff}','${ad}')`);
  await fails(`SELECT set_staff_shops('${staff}',ARRAY['${ad}'::uuid])`);
  await fails(`SELECT supprimer_vente_admin(gen_random_uuid())`);
 });
 await t.test('réservation, paiements et remise sans double vente ni double stock',async()=>{
  const r=(await scalar(`SELECT create_reservation('${kh}',1,'${prod}',2,100,'Test') id`)).id;
  assert.equal((await scalar(`SELECT reserved_quantity n FROM produits WHERE id='${prod}'`)).n,2);
  await fails(`SELECT add_payment('${ad}',${r},10,'Intrus')`);
  await fails(`SELECT add_payment('${kh}',${r},1000,'Trop')`);
  await fails(`SELECT mark_reservation_remis('${kh}',${r})`);
  await db.exec(`SELECT add_payment('${kh}',${r},900,'Solde'); SELECT mark_reservation_remis('${kh}',${r});`);
  await fails(`SELECT mark_reservation_remis('${kh}',${r})`);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,26);
  assert.equal((await scalar(`SELECT reserved_quantity n FROM produits WHERE id='${prod}'`)).n,0);
  assert.equal(Number((await scalar(`SELECT sum(amount) n FROM payments WHERE reservation_id=${r}`)).n),1000);
 });
 await login(admin);
 await t.test('commandes : plusieurs articles, doublons, stocks, snapshots, idempotence, annulation',async()=>{
  const second=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,stock_quantite,purchase_price) VALUES('${kh}','${cat}','Foulard',250,15,100) RETURNING id`)).id;
  const start=(await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n;
  const items=JSON.stringify([{product_id:prod,quantity:2,unit_price:500},{product_id:second,quantity:3,unit_price:250},{product_id:second,quantity:1,unit_price:200}]);
  const request='40000000-0000-4000-8000-000000000001';
  const sql=`SELECT create_sale_order('${kh}',1,'${items}','${request}') id`;
  const id=(await scalar(sql)).id;
  assert.equal((await scalar(sql)).id,id);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,start-2);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${second}'`)).n,11);
  assert.equal((await scalar(`SELECT count(*)::int n FROM vente_lignes WHERE sale_id='${id}'`)).n,3);
  assert.equal(Number((await scalar(`SELECT montant_total FROM ventes WHERE id='${id}'`)).montant_total),1950);
  const inv=await scalar(`SELECT * FROM factures WHERE sale_id='${id}'`);
  assert.equal(inv.items.length,3);assert.equal(Number(inv.total_amount),1950);assert.equal(Number(inv.paid_amount),1950);
  assert.equal(inv.customer_name,'Ancien client');assert.equal(inv.shop_name,'Boutique Khady Faye');
  await db.exec(`UPDATE produits SET nom_modele='Foulard renommé',purchase_price=999 WHERE id='${second}'`);
  assert.equal((await scalar(`SELECT items FROM factures WHERE sale_id='${id}'`)).items[1].product_name,'Foulard');
  assert.equal((await scalar(`SELECT items FROM factures WHERE sale_id='${id}'`)).items[1].purchase_price,100);
  await login(staff);
  await fails(`SELECT supprimer_vente_admin('${kh}','${id}')`);
  await fails(`UPDATE vente_lignes SET quantity=99 WHERE sale_id='${id}'`);
  await fails(`SELECT create_sale_order('${ad}',null,'${items}',gen_random_uuid())`);
  await fails(sql);
  await login(admin);
  await db.exec(`SELECT supprimer_vente_admin('${kh}','${id}')`);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,start);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${second}'`)).n,15);
  await fails(`SELECT supprimer_vente_admin('${kh}','${id}')`);
  assert.equal((await scalar(`SELECT count(*)::int n FROM factures WHERE sale_id='${id}'`)).n,1);
  assert.equal((await scalar(sql)).id,id);
  await fails(`SELECT create_sale_order('${kh}',null,'${items}','${request}')`);
 });
 await t.test('commande : erreur au dernier article annule tous les débits et documents',async()=>{
  const before=(await db.query('SELECT id,stock_quantite FROM produits ORDER BY id')).rows;
  const count=(await scalar('SELECT count(*)::int n FROM ventes')).n;
  for(const items of [[],[{product_id:prod,quantity:1,unit_price:10},{product_id:prod,quantity:9999,unit_price:10}],
   [{product_id:prod,quantity:1,unit_price:10},{product_id:prodAd,quantity:1,unit_price:10}],
   [{product_id:prod,quantity:1.5,unit_price:10}], [{product_id:prod,quantity:1,unit_price:-1}],
   [{product_id:prod,quantity:1,unit_price:0.001}]]) {
    await fails(`SELECT create_sale_order('${kh}',null,'${JSON.stringify(items)}',gen_random_uuid())`);
   }
  assert.deepEqual((await db.query('SELECT id,stock_quantite FROM produits ORDER BY id')).rows,before);
  assert.equal((await scalar('SELECT count(*)::int n FROM ventes')).n,count);
 });
 await t.test('commande mono-article, cliente figée, stocks réservés et annulation ancienne',async()=>{
  await db.exec(`UPDATE customers SET telephone='770000000',adresse='Dakar' WHERE id=1`);
  const items=JSON.stringify([{product_id:prod,quantity:1,unit_price:400}]);
  const start=(await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n;
  const id=(await scalar(`SELECT create_sale_order('${kh}',1,'${items}',gen_random_uuid()) id`)).id;
  const f=await scalar(`SELECT * FROM factures WHERE sale_id='${id}'`);
  assert.equal(f.items.length,1);assert.equal(f.customer_phone,'770000000');assert.equal(f.customer_address,'Dakar');
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,start-1);
  await db.exec(`SELECT supprimer_vente_admin('${kh}','${id}')`);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,start);
  const archive=await scalar('SELECT sale_id FROM factures WHERE legacy LIMIT 1');
  await db.exec(`SELECT supprimer_vente_admin('${kh}','${archive.sale_id}')`);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,start+1);
  const r=(await scalar(`SELECT create_reservation('${kh}',1,'${prod}',${start+1},0,'Tout réservé') id`)).id;
  await fails(`SELECT create_sale_order('${kh}',null,'${items}',gen_random_uuid())`);
  await db.exec(`SELECT cancel_reservation('${kh}',${r})`);
 });
 await t.test('réaffectation et désactivation retirent réellement les accès',async()=>{
  await db.exec(`SELECT set_staff_shops('${staff}',ARRAY['${am}'::uuid]);`);
  await login(staff);
  assert.equal((await scalar('SELECT id FROM shops')).id,am);
  await fails(`SELECT create_sale('${kh}','${prod}',null,1,500)`);
  await db.exec(`SELECT create_sale('${am}','${prodAm}',null,1,100)`);
  await login(admin); await db.exec(`UPDATE profiles SET active=false WHERE id='${staff}'`); await login(staff);
  assert.equal((await scalar('SELECT count(*)::int n FROM produits')).n,0);
  await fails(`SELECT record_versement('${am}',100,'Non')`);
 });
 await db.exec(`RESET ROLE; SET ROLE anon;`);
 await t.test('visiteur anonyme sans accès',async()=>{
  await fails('SELECT * FROM ventes');await fails('SELECT * FROM vente_lignes');
  await fails(`SELECT create_sale('${kh}','${prod}',null,1,500)`);
  await fails(`SELECT create_sale_order('${kh}',null,'[]',gen_random_uuid())`);
 });
 } finally {await db.close();}
});
