const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {PGlite} = require('@electric-sql/pglite');
const fixture = JSON.parse(fs.readFileSync('tests/schema-before.json','utf8').replace(/^\uFEFF/,''));
const kh='00000000-0000-4000-8000-000000000001', ad='00000000-0000-4000-8000-000000000002', am='00000000-0000-4000-8000-000000000003';
const admin='10000000-0000-4000-8000-000000000001', staff='10000000-0000-4000-8000-000000000002';
const prod='20000000-0000-4000-8000-000000000001', cat='30000000-0000-4000-8000-000000000001';
const qid = s=>'"'+s.replaceAll('"','""')+'"';
test('migration réelle : conservation, RLS, RPC, factures et réservations',async t=>{
 const db=new PGlite();
 try {
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$;
 GRANT USAGE ON SCHEMA auth TO authenticated,anon;
 CREATE FUNCTION public.uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;`);
 for(const r of fixture.relations){
   await db.exec(`CREATE TABLE public.${qid(r.name)} (${r.columns.map(c=>qid(c.name)+' '+c.type+
     (c.generated?` GENERATED ALWAYS AS (${c.default}) STORED`:c.identity?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:'')+
     (c.not_null?' NOT NULL':'')).join(',')})`);
 }
 for(const type of ['p','u','c','f']) for(const r of fixture.relations) for(const c of r.constraints.filter(c=>c.type===type))
  await db.exec(`ALTER TABLE public.${qid(r.name)} ADD CONSTRAINT ${qid(c.name)} ${c.definition}`);
 for(const f of fixture.functions) await db.exec(f.definition);
 for(const r of fixture.relations) for(const trig of r.triggers) await db.exec(trig);
 for(const p of fixture.policies.filter(p=>p.schemaname==='public')) await db.exec(`CREATE POLICY ${qid(p.policyname)} ON public.${qid(p.tablename)} FOR ${p.cmd} TO ${p.roles.map(qid).join(',')}${p.qual?' USING ('+p.qual+')':''}${p.with_check?' WITH CHECK ('+p.with_check+')':''}`);
 await db.exec(`INSERT INTO auth.users VALUES('${admin}'),('${staff}');
 INSERT INTO public.profiles(id,nom_complet,role) VALUES('${admin}','Admin','admin'),('${staff}','Personnel','vendeuse');
 INSERT INTO public.categories(id,nom) VALUES('${cat}','Ancienne catégorie');
 INSERT INTO public.produits(id,categorie_id,nom_modele,prix,stock_quantite) VALUES('${prod}','${cat}','Ancien produit',500,30);
 INSERT INTO public.customers(nom) VALUES('Ancien client');
 INSERT INTO public.ventes(produit_id,quantite,prix_unitaire,mode_paiement,vendeuse_id) VALUES('${prod}',1,500,'especes','${staff}');`);
 await db.exec(fs.readFileSync('supabase/migration-multi-boutiques.sql','utf8'));
 await db.exec(`CREATE SCHEMA storage;
 CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text,name text);
 ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
 GRANT USAGE ON SCHEMA storage TO authenticated;
 GRANT INSERT, SELECT ON storage.objects TO authenticated;`);
 await db.exec(fs.readFileSync('supabase/activer-photos-produits.sql','utf8'));
 const scalar=async sql=>(await db.query(sql)).rows[0];
 const login=async id=>{await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${id}',false); SET ROLE authenticated;`)};
 const fails=async sql=>{await assert.rejects(db.exec(sql));};
 await t.test('anciennes données conservées et rattachées à Khady',async()=>{
  assert.equal((await scalar(`SELECT count(*)::int n FROM ventes WHERE shop_id='${kh}'`)).n,1);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,29);
  assert.equal((await scalar('SELECT count(*)::int n FROM factures WHERE legacy')).n,1);
 });
 await login(admin);
 await t.test('photos privées : envoi admin, lecture par boutique et refus personnel',async()=>{
  await db.exec(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${admin}/photo.jpg'),('product-photos','${ad}/${admin}/photo.jpg')`);
  await login(staff);
  assert.equal((await scalar(`SELECT count(*)::int n FROM storage.objects`)).n,1);
  await fails(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${staff}/photo.jpg')`);
  await login(admin);
  await fails(`INSERT INTO storage.objects(bucket_id,name) VALUES('product-photos','${kh}/${staff}/photo.jpg')`);
 });
 let catAd=(await scalar(`SELECT id FROM categories WHERE shop_id='${ad}' LIMIT 1`)).id;
 let catAm=(await scalar(`SELECT id FROM categories WHERE shop_id='${am}' LIMIT 1`)).id;
 const prodAd=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,stock_quantite,purchase_price) VALUES('${ad}','${catAd}','Tissu',300,50,100) RETURNING id`)).id;
 const prodAm=(await scalar(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix,stock_quantite) VALUES('${am}','${catAm}','Assiette',100,5) RETURNING id`)).id;
 await t.test('ventes séparées, déduction unique et accès global admin',async()=>{
  await db.exec(`SELECT create_sale('${kh}','${prod}',null,1,500); SELECT create_sale('${ad}','${prodAd}',null,1,300);`);
  assert.equal((await scalar(`SELECT sum(montant_total)::int n FROM ventes WHERE shop_id='${kh}'`)).n,1000);
  assert.equal((await scalar(`SELECT sum(montant_total)::int n FROM ventes WHERE shop_id='${ad}'`)).n,300);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,28);
  assert.equal((await scalar('SELECT count(*)::int n FROM shops')).n,3);
 });
 await t.test('factures figées après renommage et annulation sans effacement',async()=>{
  await db.exec(`UPDATE produits SET nom_modele='Tissu renommé',purchase_price=200 WHERE id='${prodAd}'; UPDATE shops SET nom='Adama renommée' WHERE id='${ad}'`);
  const inv=await scalar(`SELECT * FROM factures WHERE shop_id='${ad}'`);
  assert.equal(inv.product_name,'Tissu'); assert.equal(inv.shop_name,'Boutique Adama Faye'); assert.equal(Number(inv.purchase_price),100);
  await fails(`UPDATE factures SET product_name='Falsifié' WHERE id='${inv.id}'`);
  await db.exec(`SELECT supprimer_vente_admin('${ad}','${inv.sale_id}')`);
  assert.equal((await scalar(`SELECT count(*)::int n FROM factures WHERE id='${inv.id}'`)).n,1);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prodAd}'`)).n,50);
  await fails(`SELECT supprimer_vente_admin('${ad}','${inv.sale_id}')`);
 });
 await t.test('relations inter-boutiques et déplacement refusés même à admin',async()=>{
  await fails(`INSERT INTO produits(shop_id,categorie_id,nom_modele,prix) VALUES('${kh}','${catAd}','Intrus',1)`);
  await fails(`UPDATE produits SET shop_id='${ad}',categorie_id='${catAd}' WHERE id='${prod}'`);
  await fails(`SELECT create_sale('${kh}','${prodAd}',null,1,10)`);
 });
 await login(staff);
 await t.test('personnel : lecture et RPC limitées à Khady, privilèges inviolables',async()=>{
  assert.equal((await scalar('SELECT count(*)::int n FROM shops')).n,1);
  assert.equal((await scalar(`SELECT count(*)::int n FROM produits WHERE shop_id='${ad}'`)).n,0);
  assert.equal((await scalar(`SELECT count(*)::int n FROM factures WHERE shop_id='${ad}'`)).n,0);
  await fails(`SELECT create_sale('${ad}','${prodAd}',null,1,300)`);
  await fails(`INSERT INTO customers(nom,shop_id) VALUES('Intrus','${ad}')`);
  await fails(`UPDATE profiles SET role='admin' WHERE id='${staff}'`);
  await fails(`INSERT INTO profile_shops VALUES('${staff}','${ad}')`);
  await fails(`SELECT set_staff_shops('${staff}',ARRAY['${ad}'::uuid])`);
  await fails(`SELECT supprimer_vente_admin(gen_random_uuid())`);
 });
 await t.test('réservation, paiements et remise sans double vente ni double stock',async()=>{
  const r=(await scalar(`SELECT create_reservation('${kh}',1,'${prod}',2,100,'Test') id`)).id;
  assert.equal((await scalar(`SELECT reserved_quantity n FROM produits WHERE id='${prod}'`)).n,2);
  await fails(`SELECT add_payment('${ad}',${r},10,'Intrus')`);
  await fails(`SELECT add_payment('${kh}',${r},1000,'Trop')`);
  await fails(`SELECT mark_reservation_remis('${kh}',${r})`);
  await db.exec(`SELECT add_payment('${kh}',${r},900,'Solde'); SELECT mark_reservation_remis('${kh}',${r});`);
  await fails(`SELECT mark_reservation_remis('${kh}',${r})`);
  assert.equal((await scalar(`SELECT stock_quantite n FROM produits WHERE id='${prod}'`)).n,26);
  assert.equal((await scalar(`SELECT reserved_quantity n FROM produits WHERE id='${prod}'`)).n,0);
  assert.equal(Number((await scalar(`SELECT sum(amount) n FROM payments WHERE reservation_id=${r}`)).n),1000);
 });
 await login(admin);
 await t.test('réaffectation et désactivation retirent réellement les accès',async()=>{
  await db.exec(`SELECT set_staff_shops('${staff}',ARRAY['${am}'::uuid]);`);
  await login(staff);
  assert.equal((await scalar('SELECT id FROM shops')).id,am);
  await fails(`SELECT create_sale('${kh}','${prod}',null,1,500)`);
  await db.exec(`SELECT create_sale('${am}','${prodAm}',null,1,100)`);
  await login(admin); await db.exec(`UPDATE profiles SET active=false WHERE id='${staff}'`); await login(staff);
  assert.equal((await scalar('SELECT count(*)::int n FROM produits')).n,0);
  await fails(`SELECT record_versement('${am}',100,'Non')`);
 });
 await db.exec(`RESET ROLE; SET ROLE anon;`);
 await t.test('visiteur anonyme sans accès',async()=>{await fails('SELECT * FROM ventes'); await fails(`SELECT create_sale('${kh}','${prod}',null,1,500)`)});
 } finally {await db.close();}
});
