// Parcours réel du navigateur contre PostgreSQL local éphémère. Aucun réseau métier.
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const kh='00000000-0000-4000-8000-000000000001',ad='00000000-0000-4000-8000-000000000002';
const admin='10000000-0000-4000-8000-000000000001';
const p1='20000000-0000-4000-8000-000000000001',p2='20000000-0000-4000-8000-000000000002';
const ident=s=>'"'+s.replaceAll('"','""')+'"';
async function setup(db){
 const fixture=JSON.parse(fs.readFileSync('tests/schema-before.json','utf8').replace(/^\uFEFF/,''));
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$;
 GRANT USAGE ON SCHEMA auth TO authenticated,anon;
 CREATE FUNCTION uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;`);
 for(const r of fixture.relations) await db.exec(`CREATE TABLE ${ident(r.name)} (${r.columns.map(c=>ident(c.name)+' '+c.type+(c.generated?` GENERATED ALWAYS AS (${c.default}) STORED`:c.identity?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:'')+(c.not_null?' NOT NULL':'')).join(',')})`);
 for(const type of ['p','u','c','f'])for(const r of fixture.relations)for(const c of r.constraints.filter(c=>c.type===type)) await db.exec(`ALTER TABLE ${ident(r.name)} ADD CONSTRAINT ${ident(c.name)} ${c.definition}`);
 for(const f of fixture.functions)await db.exec(f.definition);
 for(const r of fixture.relations)for(const trigger of r.triggers)await db.exec(trigger);
 await db.exec(`INSERT INTO auth.users VALUES('${admin}'); INSERT INTO profiles(id,nom_complet,role) VALUES('${admin}','Administratrice test','admin');`);
 await db.exec(fs.readFileSync('supabase/migration-multi-boutiques.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migration-ventes-multi-produits.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migration-unites-metres.sql','utf8'));
 await db.exec(`INSERT INTO produits(id,shop_id,nom_modele,prix,stock_quantite,purchase_price,categorie_id)
 SELECT x.id::uuid,x.shop::uuid,x.nom,x.prix,x.stock,x.cout,(SELECT id FROM categories WHERE shop_id=x.shop::uuid LIMIT 1) FROM (VALUES
 ('${p1}','${kh}','Ensemble brodé',5000,20,3000),('${p2}','${kh}','Foulard en soie',2500,10,1000),
 ('20000000-0000-4000-8000-000000000003','${ad}','Tissu Adama',1000,8,500)) AS x(id,shop,nom,prix,stock,cout);
 INSERT INTO customers(nom,telephone,adresse,shop_id) VALUES('Cliente de démonstration','770000000','Dakar, Sénégal','${kh}');
 SELECT set_config('request.jwt.claim.sub','${admin}',false); SET ROLE authenticated;`);
}
function browserClient(){
 return {auth:{getSession:async()=>({data:{session:{user:{id:'10000000-0000-4000-8000-000000000001',email:'demo@example.test'}}}}),onAuthStateChange(){},signOut:async()=>({})},
 rpc:(name,args={})=>window.localDb({rpc:name,args}),
 from(table){const q={table,filters:[]};const b={
  select(){return b},eq(k,v){q.filters.push([k,v,false]);return b},in(k,v){q.filters.push([k,v,true]);return b},
  order(key,options={}){q.order=[key,options.ascending!==false];return b},range(a,z){q.range=[a,z];return b},limit(n){q.limit=n;return b},
  single(){q.single=true;return b},insert(rows){q.insert=rows;return b},
  then(resolve,reject){return window.localDb(q).then(resolve,reject)}};return b;}};
}
(async()=>{
 const db=new PGlite();let browser;
 try {
 await setup(db);
 await db.exec('RESET ROLE');await db.exec(fs.readFileSync('supabase/migration-paiements-en-cours.sql','utf8'));await db.exec('SET ROLE authenticated');
 browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',msg=>{if(msg.type()==='error')console.error(msg.text());});
 page.on('dialog',dialog=>dialog.accept());
 await page.exposeFunction('localDb',async q=>{
  try {
   let sql,params=[];
   if(q.rpc){
    const args=Object.entries(q.args);
    sql=`SELECT public.${ident(q.rpc)}(${args.map(([k],i)=>ident(k)+' => $'+(i+1)).join(',')}) AS result`;
    params=args.map(([,v])=>Array.isArray(v)?JSON.stringify(v):v);
   }else if(q.insert){
    const entries=Object.entries(q.insert);params=entries.map(([,v])=>typeof v==='object'&&v!==null?JSON.stringify(v):v);
    sql=`INSERT INTO public.${ident(q.table)}(${entries.map(([k])=>ident(k)).join(',')}) VALUES(${params.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`;
   }else{
    sql=`SELECT * FROM public.${ident(q.table)}`;
    if(q.filters.length)sql+=' WHERE '+q.filters.map(([k,v,many])=>{
     if(many){if(!v.length)return 'false';return ident(k)+' IN ('+v.map(value=>{params.push(value);return '$'+params.length}).join(',')+')';}
     params.push(v);return ident(k)+'=$'+params.length;
    }).join(' AND ');
    if(q.order)sql+=' ORDER BY '+ident(q.order[0])+(q.order[1]?' ASC':' DESC');
    if(q.range)sql+=' LIMIT '+(q.range[1]-q.range[0]+1)+' OFFSET '+q.range[0];
    else if(q.limit)sql+=' LIMIT '+q.limit;
   }
   const result=await db.query(sql,params);
   return JSON.parse(JSON.stringify({data:q.rpc?result.rows[0].result:q.single?result.rows[0]:result.rows,error:null}));
  }catch(e){return {data:null,error:{message:e.message,code:e.code}};}
 });
 await page.addInitScript({content:`window.supabase={createClient:(${browserClient.toString()})};`});
 await page.route('**/*',async route=>{
  const url=new URL(route.request().url());
  if(url.hostname!=='darou.test')return route.fulfill({body:'',contentType:'text/javascript'});
  const name=url.pathname==='/'?'index.html':url.pathname.slice(1);
  if(!['index.html','style.css','units.js','script.js','shops-core.js','shops.js','invoice-pdf.js','sales-orders.js','sale-payments.js','brand.js','report-pdf.js','finance.js','periods.js','assets/darou-salam-logo.png'].includes(name))return route.fulfill({status:404,body:''});
  return route.fulfill({body:fs.readFileSync(name),contentType:name.endsWith('.png')?'image/png':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html'});
 });
 await page.goto('https://darou.test');await page.locator('#shopOverview h2').waitFor();
 await page.locator('[data-page="sales"]').click();
 await page.locator('.sale-item select').selectOption(p1);
 await page.locator('.sale-item [data-field="quantity"]').fill('2');
 await page.selectOption('#salePaymentStatus','partial');
 await page.fill('#salePaymentName','Awa Paiement');await page.fill('#salePaymentPhone','771234567');
 await page.fill('#salePaidAmount','2000');await page.selectOption('#salePaymentMethod','wave');
 const today=await page.locator('#salePaymentDate').inputValue();
 await page.fill('#saleNextDue',today);
 assert.match(await page.locator('#salePaymentRemaining').innerText(),/8.*000/);
 await page.locator('#saleForm [type="submit"]').click();
 await page.locator('#invoiceModal[open]').waitFor().catch(async e=>{console.error(await page.locator('#saleFeedback').innerText());throw e;});
 assert.match(await page.locator('#invoiceContent').innerText(),/Paiement partiel/);
 assert.match(await page.locator('#invoiceContent').innerText(),/Wave/);
 assert.match(await page.locator('#invoiceContent').innerText(),/DAROU SALAM BUSINESS/);
 assert.doesNotMatch(await page.locator('#invoiceContent').innerText(),/Invalid Date/);
 fs.mkdirSync('test-results',{recursive:true});
 let download=page.waitForEvent('download');await page.locator('#invoicePdf').click();await (await download).saveAs(path.resolve('test-results/facture-paiement-partiel.pdf'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/paiement-facture-mobile.png',fullPage:true});
 assert.ok(await page.locator('#invoiceModal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.locator('#invoiceModal button').filter({hasText:'Fermer'}).click();
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('[data-page="receivables"]').click();
 assert.equal(await page.locator('#receivablesRows tr').count(),1);
 assert.match(await page.locator('#receivablesRows').innerText(),/Awa Paiement/);
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>document.getElementById('mobileMenu').getBoundingClientRect().right<=1);
 await page.screenshot({path:'test-results/paiements-table-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('[data-payment-action="remind"]').click();
 assert.equal(await page.locator('#reminderPhone').inputValue(),'+221771234567');
 assert.match(await page.locator('#reminderMessage').inputValue(),/8.*000/);
 await page.evaluate(()=>{window.open=(...args)=>{window.preparedWhatsApp=args[0];}});
 await page.locator('#openPaymentWhatsApp').click();
 assert.match(await page.evaluate(()=>window.preparedWhatsApp),/^https:\/\/wa.me\/221771234567\?text=/);
 await page.locator('#paymentReminderModal button').filter({hasText:'Fermer'}).click();
 await page.locator('[data-payment-action="add"]').click();
 await page.fill('#newPaymentAmount','3000');await page.selectOption('#newPaymentMethod','orange_money');
 await page.locator('#salePaymentForm [type="submit"]').click();await page.locator('#invoiceModal[open]').waitFor();
 assert.match(await page.locator('#invoiceContent').innerText(),/REÇU DE VERSEMENT/);
 assert.doesNotMatch(await page.locator('#invoiceContent').innerText(),/Invalid Date/);
 assert.match(await page.locator('#invoiceContent').innerText(),/3.*000/);
 assert.match(await page.locator('#invoiceContent').innerText(),/5.*000/);
 download=page.waitForEvent('download');await page.locator('#invoicePdf').click();await (await download).saveAs(path.resolve('test-results/recu-versement.pdf'));
 await page.screenshot({path:'test-results/recu-versement-desktop.png',fullPage:true});
 await page.evaluate(()=>{window.print=()=>{window.receiptPrinted=true;}});await page.locator('#invoicePrint').click();
 assert.equal(await page.evaluate(()=>window.receiptPrinted),true);
 await page.locator('[data-payment-action="settle"]').click();assert.equal(await page.locator('#newPaymentAmount').inputValue(),'5000');
 await page.locator('#salePaymentForm [type="submit"]').click();await page.locator('#invoiceModal[open]').waitFor();
 assert.match(await page.locator('#invoiceContent').innerText(),/Payé/);
 await page.locator('#invoiceModal button').filter({hasText:'Fermer'}).click();
 await page.selectOption('#receivablesFilter','paid');assert.match(await page.locator('#receivablesRows').innerText(),/Payé/);
 await page.locator('[data-payment-action="history"]').click();assert.equal(await page.locator('#paymentHistoryContent [data-receipt]').count(),3);
 await page.locator('#paymentHistoryContent [data-receipt]').first().click();
 assert.match(await page.locator('#invoiceContent').innerText(),/8.*000/); // premier reçu inchangé après solde
 await page.locator('#invoiceModal button').filter({hasText:'Fermer'}).click();
 assert.equal(Number((await db.query('SELECT count(*) n FROM sale_payment_entries')).rows[0].n),3);
 assert.equal(Number((await db.query('SELECT stock_quantite n FROM produits WHERE id=$1',[p1])).rows[0].n),18);
 await page.selectOption('#shopSelector',ad);await page.waitForFunction(()=>document.querySelector('#shopOverview h2')?.textContent==='Boutique Adama Faye');
 await page.locator('[data-page="receivables"]').click();assert.match(await page.locator('#receivablesRows').innerText(),/Aucun paiement/);
 assert.deepEqual(errors,[]);
 console.log('Paiements navigateur : vente partielle, versements, solde, historique, reçus PDF, impression, mobile, rappel préparé et isolation boutique validés.');
 }finally{if(browser)await browser.close();await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
