const fs=require('node:fs');
const kh='00000000-0000-4000-8000-000000000001',ad='00000000-0000-4000-8000-000000000002';
const admin='10000000-0000-4000-8000-000000000001';
const p1='20000000-0000-4000-8000-000000000001',p2='20000000-0000-4000-8000-000000000002';
const ident=s=>'"'+s.replaceAll('"','""')+'"';
async function setup(db){
 const fixture=JSON.parse(fs.readFileSync('tests/schema-before.json','utf8').replace(/^\uFEFF/,''));
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$;
 GRANT USAGE ON SCHEMA auth TO authenticated,anon;
 CREATE FUNCTION uuid_generate_v4() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$;`);
 for(const r of fixture.relations) await db.exec(`CREATE TABLE ${ident(r.name)} (${r.columns.map(c=>ident(c.name)+' '+c.type+(c.generated?` GENERATED ALWAYS AS (${c.default}) STORED`:c.identity?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:'')+(c.not_null?' NOT NULL':'')).join(',')})`);
 for(const type of ['p','u','c','f'])for(const r of fixture.relations)for(const c of r.constraints.filter(c=>c.type===type)) await db.exec(`ALTER TABLE ${ident(r.name)} ADD CONSTRAINT ${ident(c.name)} ${c.definition}`);
 for(const f of fixture.functions)await db.exec(f.definition);
 for(const r of fixture.relations)for(const trigger of r.triggers)await db.exec(trigger);
 await db.exec(`INSERT INTO auth.users VALUES('${admin}'); INSERT INTO profiles(id,nom_complet,role) VALUES('${admin}','Administratrice test','admin');`);
 await db.exec(fs.readFileSync('supabase/migration-multi-boutiques.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migration-ventes-multi-produits.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migration-unites-metres.sql','utf8'));
 await db.exec(`INSERT INTO produits(id,shop_id,nom_modele,prix,stock_quantite,purchase_price,categorie_id)
 SELECT x.id::uuid,x.shop::uuid,x.nom,x.prix,x.stock,x.cout,(SELECT id FROM categories WHERE shop_id=x.shop::uuid LIMIT 1) FROM (VALUES
 ('${p1}','${kh}','Ensemble brodé',5000,20,3000),('${p2}','${kh}','Foulard en soie',2500,10,1000),
 ('20000000-0000-4000-8000-000000000003','${ad}','Tissu Adama',1000,8,500)) AS x(id,shop,nom,prix,stock,cout);
 INSERT INTO customers(nom,telephone,adresse,shop_id) VALUES('Cliente de démonstration','770000000','Dakar, Sénégal','${kh}');
 SELECT set_config('request.jwt.claim.sub','${admin}',false); SET ROLE authenticated;`);
}

module.exports={setup,kh,ad,admin,p1,p2};
